Setting up Drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
%cd /content/drive

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive


In [ ]:
#!pwd


Importing Dataset and dropping columns

In [ ]:
import pandas as pd

trainPath = '/content/drive/MyDrive/ML_Project/training.csv'
df = pd.read_csv(trainPath)

#droping columns - state, Next_Year_Crime_Rate
df1 = df.drop(['state', 'Next_Year_Crime_Rate'], axis=1)
print(df1.head(5))
print(df.head(5))
#use df1

   Unnamed: 0  Alabama  Alaska  ...  Crime Rate  Top_10  Next_Year_Top_10
0           0        0       1  ...   11.595919       1               1.0
1           1        0       1  ...   16.487810       1               1.0
2           2        0       1  ...   16.681272       1               1.0
3           3        0       1  ...   15.150988       1               1.0
4           4        0       1  ...   10.122600       1               1.0

[5 rows x 212 columns]
   Unnamed: 0  Alabama  Alaska  ...  Top_10  Next_Year_Top_10  Next_Year_Crime_Rate
0           0        0       1  ...       1               1.0             16.487810
1           1        0       1  ...       1               1.0             16.681272
2           2        0       1  ...       1               1.0             15.150988
3           3        0       1  ...       1               1.0             10.122600
4           4        0       1  ...       1               1.0              9.389760

[5 rows x 214 columns]


Splitting training and validation data

In [ ]:
#for validation data
from sklearn.model_selection import train_test_split
import numpy as np

x = df1.drop('Next_Year_Top_10',axis=1).to_numpy()
y = df1['Next_Year_Top_10'].to_numpy()

x_train, x_test, y_train, y_test = train_test_split(x,y)

# ***Using Standard Scaler***

In [ ]:
#scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x_train)
x_train= scaler.transform(x_train)
x_test= scaler.transform(x_test)

Model

In [ ]:
from sklearn.linear_model import LogisticRegression

logisticReg = LogisticRegression(solver='lbfgs', max_iter=10000)
logisticReg.fit(x_train,y_train)

LogisticRegression(max_iter=10000)

In [ ]:
y_pred = logisticReg.predict(x_test)

Evaluation Metrics for Validation testing

In [ ]:
from sklearn.metrics import confusion_matrix
conf_matrix = confusion_matrix(y_test, y_pred)
conf_matrix

array([[281,  23],
       [ 22,  44]])

In [ ]:
from sklearn.metrics import classification_report, hamming_loss

hloss = hamming_loss(y_test, y_pred)
print(f'Hamming Loss: {hloss}\n\n')
print(classification_report(y_test,y_pred))

Hamming Loss: 0.12162162162162163


              precision    recall  f1-score   support

         0.0       0.93      0.92      0.93       304
         1.0       0.66      0.67      0.66        66

    accuracy                           0.88       370
   macro avg       0.79      0.80      0.79       370
weighted avg       0.88      0.88      0.88       370



With the Testing File

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
%cd /content/drive

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive


In [ ]:
#loading test data
import pandas as pd
testPath = '/content/drive/MyDrive/ML_Project/testing.csv'
dfTest = pd.read_csv(testPath)

#dropping columns
dfTest1 = dfTest.drop(['state', 'Next_Year_Crime_Rate'], axis=1)

In [ ]:
x1 = df1.drop('Next_Year_Top_10',axis=1).to_numpy()
y1 = df1['Next_Year_Top_10'].to_numpy()

x1_train, x1_test, y1_train, y1_test = train_test_split(x1,y1)

In [ ]:
#prediction on test
y_pred_test = logisticReg.predict(x1_test)

In [ ]:
#Evaluation for testing.csv

hloss_test = hamming_loss(y1_test, y_pred_test)

print(f'Hamming Loss: {hloss_test} \n\n')
print(classification_report(y1_test, y_pred_test))

Hamming Loss: 0.5783783783783784 


              precision    recall  f1-score   support

         0.0       0.92      0.32      0.48       302
         1.0       0.22      0.87      0.36        68

    accuracy                           0.42       370
   macro avg       0.57      0.59      0.42       370
weighted avg       0.79      0.42      0.45       370



In [ ]:
from sklearn.metrics import confusion_matrix

conf_matrix = confusion_matrix(y1_test, y_pred_test)
print(conf_matrix)

[[ 97 205]
 [  9  59]]


# *Scaling Years Column*

In [ ]:
#importing dataset

import pandas as pd

trainPath = '/content/drive/MyDrive/ML_Project/training.csv'
df_train = pd.read_csv(trainPath)

testPath = '/content/drive/MyDrive/ML_Project/testing.csv'
df_test = pd.read_csv(testPath)

#droping columns - state, Next_Year_Crime_Rate
train = df_train.drop(['state', 'Next_Year_Crime_Rate'], axis=1)
test = df_test.drop(['state', 'Next_Year_Crime_Rate'], axis=1)


In [ ]:
x_train1 = train.drop(['Next_Year_Top_10'], axis = 1)
x_test1 = test.drop(['Next_Year_Top_10'], axis=1)

y_train1 = train['Next_Year_Top_10']
y_test1 = test['Next_Year_Top_10']

scaling "year" column

In [ ]:
x_train1["year"] = [(1 + (i-1980)) for i in x_train1["year"]]
x_test1["year"] = [(1 + (i-1980)) for i in x_test1["year"]]

In [ ]:
from sklearn.linear_model import LogisticRegression
logisticReg2 = LogisticRegression(max_iter=10000)
logisticReg2.fit(x_train1,y_train1)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression(max_iter=10000)

In [ ]:
pred = logisticReg2.predict(x_test1)

In [ ]:
#Evaluation
from sklearn.metrics import hamming_loss, classification_report
hloss2 = hamming_loss(y_test1, pred)

print(f'Hamming Loss: {hloss2} \n\n')
print(classification_report(y_test1, pred))

Hamming Loss: 0.12156862745098039 


              precision    recall  f1-score   support

         0.0       0.91      0.94      0.93       205
         1.0       0.72      0.62      0.67        50

    accuracy                           0.88       255
   macro avg       0.82      0.78      0.80       255
weighted avg       0.87      0.88      0.87       255



In [ ]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_test1, pred))

[[193  12]
 [ 19  31]]
